version: '3'
services:
  lamp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "[HOST WWW PORT NUMBER]:80"
      - "[HOST DB PORT NUMBER]:3306"
    volumes:
      - "[HOST WWW DOCUMENT ROOT]:/var/www/html"
      - "[HOST DB DOCUMENT ROOT]:/var/lib/mysql"
